title: Julia Liu -- Project On Slender Particle Dynamics (May 2025 - Present)
theme: midnight
description: This is a collection of the documents detailing the derivation processes from my project on slender particle dynamics in flows, advised by Dr. Wenzheng Shi from NYU Courant. This collection will be updated as I progress through my work.
